### ISSUE TITLE
Java processes are not getting killed

### ISSUE THREAD

**Issue by kannang83** [DSC-SPIDAL/twister2#730] opened 2019-11-08 17:11 UTC
If the Twister2 job fails in the Juliet Cluster the Java processes are not getting killed and it affects the NFS. Also, sometimes MPI processes are not getting killed.

**Comment by supunkamburugamuve** [comment] 2019-11-23 01:33
@chathurawidanage is tihs fixed now?

**Comment by chathurawidanage** [comment] 2019-11-23 02:59
No. This problem is still there.

**Comment by supunkamburugamuve** [comment] 2019-11-23 19:00
@chathurawidanage how do we reproduce this? I cannot reproduce it now.

**Comment by chathurawidanage** [comment] 2019-11-23 19:30
This occurs mostly when one worker fails due to out of memory. Can you try
a system.exit in one of the workers.

**Comment by supunkamburugamuve** [comment] 2019-11-24 23:18
I tried with OOM. But the processes finish. I couldn't test with System.exit() though.

**Comment by chathurawidanage** [comment] 2019-11-25 01:53
I think I found the exact cause for this issue, but not sure about a proper solution for this. The barrier call just before the finalize call prevents failed worker from calling finalize(). Other workers keep calling progress since they can't proceed as iSends posted to the failed worker will never get resolved. Here is a simple code that replicates the exact issue with twister2. Ultimately, failed worker blocks on barrier(), others keep calling progress() in an unending loop.

```java
MPI.Init(args);

        final int rank = MPI.COMM_WORLD.getRank();

        System.out.println("Spinning " + rank);
        new Thread(() -> {
            try {
                Request request = MPI.COMM_WORLD.iSend(MPI.newByteBuffer(10), 0, MPI.BYTE, 0, 0);
                boolean progress = true;
                try {
                    while (progress) {
                        if (rank == 0) {
                            Thread.sleep(10000);
                            throw new RuntimeException("Twister2 Exception");
                        }
                        boolean test = request.test();
                        System.out.println("Looping... " + test);
                        Thread.sleep(1000);
                    }
                } catch (RuntimeException re) {
                    re.printStackTrace();
                } finally { // we do this in twister2
                    MPI.COMM_WORLD.barrier();
                    MPI.Finalize();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
```

**Comment by supunkamburugamuve** [comment] 2019-11-25 02:05
Great. Lets remove the barrier and see what happens. Since now the process exitis, the iSends should give an error.

**Comment by chathurawidanage** [comment] 2019-11-28 00:21
This is fixed now.

**Closed by chathurawidanage** 2019-11-28 00:21 UTC
